export interface LocationOption {
  city?: string;
  state: string;
  stateFullName: string;
  zipCode?: string;
  displayText: string;
  type: 'city' | 'state';
}

export const US_CITIES_DATA: LocationOption[] = [
  // States (for when someone types just the state)
  { state: 'AL', stateFullName: 'Alabama', displayText: 'Alabama', type: 'state' },
  { state: 'AK', stateFullName: 'Alaska', displayText: 'Alaska', type: 'state' },
  { state: 'AZ', stateFullName: 'Arizona', displayText: 'Arizona', type: 'state' },
  { state: 'AR', stateFullName: 'Arkansas', displayText: 'Arkansas', type: 'state' },
  { state: 'CA', stateFullName: 'California', displayText: 'California', type: 'state' },
  { state: 'CO', stateFullName: 'Colorado', displayText: 'Colorado', type: 'state' },
  { state: 'CT', stateFullName: 'Connecticut', displayText: 'Connecticut', type: 'state' },
  { state: 'DE', stateFullName: 'Delaware', displayText: 'Delaware', type: 'state' },
  { state: 'FL', stateFullName: 'Florida', displayText: 'Florida', type: 'state' },
  { state: 'GA', stateFullName: 'Georgia', displayText: 'Georgia', type: 'state' },
  { state: 'HI', stateFullName: 'Hawaii', displayText: 'Hawaii', type: 'state' },
  { state: 'ID', stateFullName: 'Idaho', displayText: 'Idaho', type: 'state' },
  { state: 'IL', stateFullName: 'Illinois', displayText: 'Illinois', type: 'state' },
  { state: 'IN', stateFullName: 'Indiana', displayText: 'Indiana', type: 'state' },
  { state: 'IA', stateFullName: 'Iowa', displayText: 'Iowa', type: 'state' },
  { state: 'KS', stateFullName: 'Kansas', displayText: 'Kansas', type: 'state' },
  { state: 'KY', stateFullName: 'Kentucky', displayText: 'Kentucky', type: 'state' },
  { state: 'LA', stateFullName: 'Louisiana', displayText: 'Louisiana', type: 'state' },
  { state: 'ME', stateFullName: 'Maine', displayText: 'Maine', type: 'state' },
  { state: 'MD', stateFullName: 'Maryland', displayText: 'Maryland', type: 'state' },
  { state: 'MA', stateFullName: 'Massachusetts', displayText: 'Massachusetts', type: 'state' },
  { state: 'MI', stateFullName: 'Michigan', displayText: 'Michigan', type: 'state' },
  { state: 'MN', stateFullName: 'Minnesota', displayText: 'Minnesota', type: 'state' },
  { state: 'MS', stateFullName: 'Mississippi', displayText: 'Mississippi', type: 'state' },
  { state: 'MO', stateFullName: 'Missouri', displayText: 'Missouri', type: 'state' },
  { state: 'MT', stateFullName: 'Montana', displayText: 'Montana', type: 'state' },
  { state: 'NE', stateFullName: 'Nebraska', displayText: 'Nebraska', type: 'state' },
  { state: 'NV', stateFullName: 'Nevada', displayText: 'Nevada', type: 'state' },
  { state: 'NH', stateFullName: 'New Hampshire', displayText: 'New Hampshire', type: 'state' },
  { state: 'NJ', stateFullName: 'New Jersey', displayText: 'New Jersey', type: 'state' },
  { state: 'NM', stateFullName: 'New Mexico', displayText: 'New Mexico', type: 'state' },
  { state: 'NY', stateFullName: 'New York', displayText: 'New York', type: 'state' },
  { state: 'NC', stateFullName: 'North Carolina', displayText: 'North Carolina', type: 'state' },
  { state: 'ND', stateFullName: 'North Dakota', displayText: 'North Dakota', type: 'state' },
  { state: 'OH', stateFullName: 'Ohio', displayText: 'Ohio', type: 'state' },
  { state: 'OK', stateFullName: 'Oklahoma', displayText: 'Oklahoma', type: 'state' },
  { state: 'OR', stateFullName: 'Oregon', displayText: 'Oregon', type: 'state' },
  { state: 'PA', stateFullName: 'Pennsylvania', displayText: 'Pennsylvania', type: 'state' },
  { state: 'RI', stateFullName: 'Rhode Island', displayText: 'Rhode Island', type: 'state' },
  { state: 'SC', stateFullName: 'South Carolina', displayText: 'South Carolina', type: 'state' },
  { state: 'SD', stateFullName: 'South Dakota', displayText: 'South Dakota', type: 'state' },
  { state: 'TN', stateFullName: 'Tennessee', displayText: 'Tennessee', type: 'state' },
  { state: 'TX', stateFullName: 'Texas', displayText: 'Texas', type: 'state' },
  { state: 'UT', stateFullName: 'Utah', displayText: 'Utah', type: 'state' },
  { state: 'VT', stateFullName: 'Vermont', displayText: 'Vermont', type: 'state' },
  { state: 'VA', stateFullName: 'Virginia', displayText: 'Virginia', type: 'state' },
  { state: 'WA', stateFullName: 'Washington', displayText: 'Washington', type: 'state' },
  { state: 'WV', stateFullName: 'West Virginia', displayText: 'West Virginia', type: 'state' },
  { state: 'WI', stateFullName: 'Wisconsin', displayText: 'Wisconsin', type: 'state' },
  { state: 'WY', stateFullName: 'Wyoming', displayText: 'Wyoming', type: 'state' },
  { state: 'DC', stateFullName: 'District of Columbia', displayText: 'Washington, DC', type: 'state' },

  // Major cities
  // California
  { city: 'Los Angeles', state: 'CA', stateFullName: 'California', zipCode: '90210', displayText: 'Los Angeles, CA', type: 'city' },
  { city: 'San Francisco', state: 'CA', stateFullName: 'California', zipCode: '94101', displayText: 'San Francisco, CA', type: 'city' },
  { city: 'San Diego', state: 'CA', stateFullName: 'California', zipCode: '92101', displayText: 'San Diego, CA', type: 'city' },
  { city: 'Sacramento', state: 'CA', stateFullName: 'California', zipCode: '95814', displayText: 'Sacramento, CA', type: 'city' },
  { city: 'San Jose', state: 'CA', stateFullName: 'California', zipCode: '95110', displayText: 'San Jose, CA', type: 'city' },
  { city: 'Fresno', state: 'CA', stateFullName: 'California', zipCode: '93721', displayText: 'Fresno, CA', type: 'city' },
  { city: 'Long Beach', state: 'CA', stateFullName: 'California', zipCode: '90802', displayText: 'Long Beach, CA', type: 'city' },
  { city: 'Oakland', state: 'CA', stateFullName: 'California', zipCode: '94612', displayText: 'Oakland, CA', type: 'city' },
  { city: 'Irvine', state: 'CA', stateFullName: 'California', zipCode: '92614', displayText: 'Irvine, CA', type: 'city' },
  
  // New York
  { city: 'New York', state: 'NY', stateFullName: 'New York', zipCode: '10001', displayText: 'New York, NY', type: 'city' },
  { city: 'Buffalo', state: 'NY', stateFullName: 'New York', zipCode: '14201', displayText: 'Buffalo, NY', type: 'city' },
  { city: 'Rochester', state: 'NY', stateFullName: 'New York', zipCode: '14604', displayText: 'Rochester, NY', type: 'city' },
  { city: 'Syracuse', state: 'NY', stateFullName: 'New York', zipCode: '13202', displayText: 'Syracuse, NY', type: 'city' },
  { city: 'Albany', state: 'NY', stateFullName: 'New York', zipCode: '12207', displayText: 'Albany, NY', type: 'city' },

  // Texas
  { city: 'Houston', state: 'TX', stateFullName: 'Texas', zipCode: '77001', displayText: 'Houston, TX', type: 'city' },
  { city: 'Dallas', state: 'TX', stateFullName: 'Texas', zipCode: '75201', displayText: 'Dallas, TX', type: 'city' },
  { city: 'Austin', state: 'TX', stateFullName: 'Texas', zipCode: '73301', displayText: 'Austin, TX', type: 'city' },
  { city: 'San Antonio', state: 'TX', stateFullName: 'Texas', zipCode: '78205', displayText: 'San Antonio, TX', type: 'city' },
  { city: 'Fort Worth', state: 'TX', stateFullName: 'Texas', zipCode: '76102', displayText: 'Fort Worth, TX', type: 'city' },

  // Florida
  { city: 'Miami', state: 'FL', stateFullName: 'Florida', zipCode: '33101', displayText: 'Miami, FL', type: 'city' },
  { city: 'Jacksonville', state: 'FL', stateFullName: 'Florida', zipCode: '32201', displayText: 'Jacksonville, FL', type: 'city' },
  { city: 'Tampa', state: 'FL', stateFullName: 'Florida', zipCode: '33602', displayText: 'Tampa, FL', type: 'city' },
  { city: 'Orlando', state: 'FL', stateFullName: 'Florida', zipCode: '32801', displayText: 'Orlando, FL', type: 'city' },
  { city: 'Tallahassee', state: 'FL', stateFullName: 'Florida', zipCode: '32301', displayText: 'Tallahassee, FL', type: 'city' },

  // Illinois
  { city: 'Chicago', state: 'IL', stateFullName: 'Illinois', zipCode: '60601', displayText: 'Chicago, IL', type: 'city' },
  { city: 'Springfield', state: 'IL', stateFullName: 'Illinois', zipCode: '62701', displayText: 'Springfield, IL', type: 'city' },
  { city: 'Rockford', state: 'IL', stateFullName: 'Illinois', zipCode: '61101', displayText: 'Rockford, IL', type: 'city' },

  // Other major cities
  { city: 'Atlanta', state: 'GA', stateFullName: 'Georgia', zipCode: '30301', displayText: 'Atlanta, GA', type: 'city' },
  { city: 'Boston', state: 'MA', stateFullName: 'Massachusetts', zipCode: '02101', displayText: 'Boston, MA', type: 'city' },
  { city: 'Seattle', state: 'WA', stateFullName: 'Washington', zipCode: '98101', displayText: 'Seattle, WA', type: 'city' },
  { city: 'Denver', state: 'CO', stateFullName: 'Colorado', zipCode: '80201', displayText: 'Denver, CO', type: 'city' },
  { city: 'Las Vegas', state: 'NV', stateFullName: 'Nevada', zipCode: '89101', displayText: 'Las Vegas, NV', type: 'city' },
  { city: 'Phoenix', state: 'AZ', stateFullName: 'Arizona', zipCode: '85001', displayText: 'Phoenix, AZ', type: 'city' },
  { city: 'Philadelphia', state: 'PA', stateFullName: 'Pennsylvania', zipCode: '19101', displayText: 'Philadelphia, PA', type: 'city' },
  { city: 'Nashville', state: 'TN', stateFullName: 'Tennessee', zipCode: '37201', displayText: 'Nashville, TN', type: 'city' },
  { city: 'Portland', state: 'OR', stateFullName: 'Oregon', zipCode: '97201', displayText: 'Portland, OR', type: 'city' },
  { city: 'Detroit', state: 'MI', stateFullName: 'Michigan', zipCode: '48201', displayText: 'Detroit, MI', type: 'city' },
  { city: 'Memphis', state: 'TN', stateFullName: 'Tennessee', zipCode: '38103', displayText: 'Memphis, TN', type: 'city' },
  { city: 'Louisville', state: 'KY', stateFullName: 'Kentucky', zipCode: '40202', displayText: 'Louisville, KY', type: 'city' },
  { city: 'Baltimore', state: 'MD', stateFullName: 'Maryland', zipCode: '21201', displayText: 'Baltimore, MD', type: 'city' },
  { city: 'Milwaukee', state: 'WI', stateFullName: 'Wisconsin', zipCode: '53201', displayText: 'Milwaukee, WI', type: 'city' },
  { city: 'Albuquerque', state: 'NM', stateFullName: 'New Mexico', zipCode: '87101', displayText: 'Albuquerque, NM', type: 'city' },
  { city: 'Tucson', state: 'AZ', stateFullName: 'Arizona', zipCode: '85701', displayText: 'Tucson, AZ', type: 'city' },
  { city: 'Kansas City', state: 'MO', stateFullName: 'Missouri', zipCode: '64101', displayText: 'Kansas City, MO', type: 'city' },
  { city: 'Mesa', state: 'AZ', stateFullName: 'Arizona', zipCode: '85201', displayText: 'Mesa, AZ', type: 'city' },
  { city: 'Virginia Beach', state: 'VA', stateFullName: 'Virginia', zipCode: '23451', displayText: 'Virginia Beach, VA', type: 'city' },
  { city: 'Omaha', state: 'NE', stateFullName: 'Nebraska', zipCode: '68102', displayText: 'Omaha, NE', type: 'city' },
  { city: 'Cleveland', state: 'OH', stateFullName: 'Ohio', zipCode: '44101', displayText: 'Cleveland, OH', type: 'city' },
  { city: 'Raleigh', state: 'NC', stateFullName: 'North Carolina', zipCode: '27601', displayText: 'Raleigh, NC', type: 'city' },
  { city: 'Miami Beach', state: 'FL', stateFullName: 'Florida', zipCode: '33139', displayText: 'Miami Beach, FL', type: 'city' },
  { city: 'Honolulu', state: 'HI', stateFullName: 'Hawaii', zipCode: '96813', displayText: 'Honolulu, HI', type: 'city' },
  { city: 'Minneapolis', state: 'MN', stateFullName: 'Minnesota', zipCode: '55401', displayText: 'Minneapolis, MN', type: 'city' },
  { city: 'Tulsa', state: 'OK', stateFullName: 'Oklahoma', zipCode: '74103', displayText: 'Tulsa, OK', type: 'city' },
  { city: 'Arlington', state: 'TX', stateFullName: 'Texas', zipCode: '76010', displayText: 'Arlington, TX', type: 'city' },
  { city: 'New Orleans', state: 'LA', stateFullName: 'Louisiana', zipCode: '70112', displayText: 'New Orleans, LA', type: 'city' },
  { city: 'Wichita', state: 'KS', stateFullName: 'Kansas', zipCode: '67202', displayText: 'Wichita, KS', type: 'city' },
  { city: 'Cleveland', state: 'OH', stateFullName: 'Ohio', zipCode: '44101', displayText: 'Cleveland, OH', type: 'city' },
  { city: 'Tampa', state: 'FL', stateFullName: 'Florida', zipCode: '33602', displayText: 'Tampa, FL', type: 'city' },
  { city: 'Anaheim', state: 'CA', stateFullName: 'California', zipCode: '92805', displayText: 'Anaheim, CA', type: 'city' },
  { city: 'Santa Ana', state: 'CA', stateFullName: 'California', zipCode: '92701', displayText: 'Santa Ana, CA', type: 'city' },
  { city: 'St. Louis', state: 'MO', stateFullName: 'Missouri', zipCode: '63101', displayText: 'St. Louis, MO', type: 'city' },
  { city: 'Riverside', state: 'CA', stateFullName: 'California', zipCode: '92501', displayText: 'Riverside, CA', type: 'city' },
  { city: 'Corpus Christi', state: 'TX', stateFullName: 'Texas', zipCode: '78401', displayText: 'Corpus Christi, TX', type: 'city' },
  { city: 'Lexington', state: 'KY', stateFullName: 'Kentucky', zipCode: '40507', displayText: 'Lexington, KY', type: 'city' },
  { city: 'Pittsburgh', state: 'PA', stateFullName: 'Pennsylvania', zipCode: '15219', displayText: 'Pittsburgh, PA', type: 'city' },
  { city: 'Anchorage', state: 'AK', stateFullName: 'Alaska', zipCode: '99501', displayText: 'Anchorage, AK', type: 'city' },
  { city: 'Stockton', state: 'CA', stateFullName: 'California', zipCode: '95202', displayText: 'Stockton, CA', type: 'city' },
  { city: 'Cincinnati', state: 'OH', stateFullName: 'Ohio', zipCode: '45202', displayText: 'Cincinnati, OH', type: 'city' },
  { city: 'St. Paul', state: 'MN', stateFullName: 'Minnesota', zipCode: '55101', displayText: 'St. Paul, MN', type: 'city' },
  { city: 'Toledo', state: 'OH', stateFullName: 'Ohio', zipCode: '43604', displayText: 'Toledo, OH', type: 'city' },
  { city: 'Greensboro', state: 'NC', stateFullName: 'North Carolina', zipCode: '27401', displayText: 'Greensboro, NC', type: 'city' },
  { city: 'Newark', state: 'NJ', stateFullName: 'New Jersey', zipCode: '07102', displayText: 'Newark, NJ', type: 'city' },
  { city: 'Plano', state: 'TX', stateFullName: 'Texas', zipCode: '75023', displayText: 'Plano, TX', type: 'city' },
  { city: 'Henderson', state: 'NV', stateFullName: 'Nevada', zipCode: '89011', displayText: 'Henderson, NV', type: 'city' },
  { city: 'Lincoln', state: 'NE', stateFullName: 'Nebraska', zipCode: '68508', displayText: 'Lincoln, NE', type: 'city' },
  { city: 'Buffalo', state: 'NY', stateFullName: 'New York', zipCode: '14201', displayText: 'Buffalo, NY', type: 'city' },
  { city: 'Jersey City', state: 'NJ', stateFullName: 'New Jersey', zipCode: '07302', displayText: 'Jersey City, NJ', type: 'city' },
  { city: 'Chula Vista', state: 'CA', stateFullName: 'California', zipCode: '91910', displayText: 'Chula Vista, CA', type: 'city' },
  { city: 'Fort Wayne', state: 'IN', stateFullName: 'Indiana', zipCode: '46802', displayText: 'Fort Wayne, IN', type: 'city' },
  { city: 'Orlando', state: 'FL', stateFullName: 'Florida', zipCode: '32801', displayText: 'Orlando, FL', type: 'city' },
  { city: 'St. Petersburg', state: 'FL', stateFullName: 'Florida', zipCode: '33701', displayText: 'St. Petersburg, FL', type: 'city' },
  { city: 'Chandler', state: 'AZ', stateFullName: 'Arizona', zipCode: '85225', displayText: 'Chandler, AZ', type: 'city' },
  { city: 'Laredo', state: 'TX', stateFullName: 'Texas', zipCode: '78040', displayText: 'Laredo, TX', type: 'city' },
  { city: 'Norfolk', state: 'VA', stateFullName: 'Virginia', zipCode: '23510', displayText: 'Norfolk, VA', type: 'city' },
  { city: 'Durham', state: 'NC', stateFullName: 'North Carolina', zipCode: '27701', displayText: 'Durham, NC', type: 'city' },
  { city: 'Madison', state: 'WI', stateFullName: 'Wisconsin', zipCode: '53703', displayText: 'Madison, WI', type: 'city' },
  { city: 'Lubbock', state: 'TX', stateFullName: 'Texas', zipCode: '79401', displayText: 'Lubbock, TX', type: 'city' },
  { city: 'Irvine', state: 'CA', stateFullName: 'California', zipCode: '92614', displayText: 'Irvine, CA', type: 'city' },
  { city: 'Winston-Salem', state: 'NC', stateFullName: 'North Carolina', zipCode: '27101', displayText: 'Winston-Salem, NC', type: 'city' },
  { city: 'Glendale', state: 'AZ', stateFullName: 'Arizona', zipCode: '85301', displayText: 'Glendale, AZ', type: 'city' },
  { city: 'Garland', state: 'TX', stateFullName: 'Texas', zipCode: '75040', displayText: 'Garland, TX', type: 'city' },
  { city: 'Hialeah', state: 'FL', stateFullName: 'Florida', zipCode: '33010', displayText: 'Hialeah, FL', type: 'city' },
  { city: 'Reno', state: 'NV', stateFullName: 'Nevada', zipCode: '89501', displayText: 'Reno, NV', type: 'city' },
  { city: 'Chesapeake', state: 'VA', stateFullName: 'Virginia', zipCode: '23320', displayText: 'Chesapeake, VA', type: 'city' },
  { city: 'Gilbert', state: 'AZ', stateFullName: 'Arizona', zipCode: '85234', displayText: 'Gilbert, AZ', type: 'city' },
  { city: 'Baton Rouge', state: 'LA', stateFullName: 'Louisiana', zipCode: '70801', displayText: 'Baton Rouge, LA', type: 'city' },
  { city: 'Irving', state: 'TX', stateFullName: 'Texas', zipCode: '75061', displayText: 'Irving, TX', type: 'city' },
  { city: 'Scottsdale', state: 'AZ', stateFullName: 'Arizona', zipCode: '85251', displayText: 'Scottsdale, AZ', type: 'city' },
  { city: 'North Las Vegas', state: 'NV', stateFullName: 'Nevada', zipCode: '89030', displayText: 'North Las Vegas, NV', type: 'city' },
  { city: 'Fremont', state: 'CA', stateFullName: 'California', zipCode: '94536', displayText: 'Fremont, CA', type: 'city' },
  { city: 'Boise', state: 'ID', stateFullName: 'Idaho', zipCode: '83702', displayText: 'Boise, ID', type: 'city' },
  { city: 'Richmond', state: 'VA', stateFullName: 'Virginia', zipCode: '23220', displayText: 'Richmond, VA', type: 'city' },
  { city: 'San Bernardino', state: 'CA', stateFullName: 'California', zipCode: '92401', displayText: 'San Bernardino, CA', type: 'city' },
  { city: 'Birmingham', state: 'AL', stateFullName: 'Alabama', zipCode: '35203', displayText: 'Birmingham, AL', type: 'city' },
  { city: 'Spokane', state: 'WA', stateFullName: 'Washington', zipCode: '99201', displayText: 'Spokane, WA', type: 'city' },
  { city: 'Rochester', state: 'NY', stateFullName: 'New York', zipCode: '14604', displayText: 'Rochester, NY', type: 'city' },
  { city: 'Des Moines', state: 'IA', stateFullName: 'Iowa', zipCode: '50309', displayText: 'Des Moines, IA', type: 'city' },
  { city: 'Modesto', state: 'CA', stateFullName: 'California', zipCode: '95354', displayText: 'Modesto, CA', type: 'city' },
  { city: 'Fayetteville', state: 'NC', stateFullName: 'North Carolina', zipCode: '28301', displayText: 'Fayetteville, NC', type: 'city' },
  { city: 'Tacoma', state: 'WA', stateFullName: 'Washington', zipCode: '98402', displayText: 'Tacoma, WA', type: 'city' },
  { city: 'Oxnard', state: 'CA', stateFullName: 'California', zipCode: '93030', displayText: 'Oxnard, CA', type: 'city' },
  { city: 'Fontana', state: 'CA', stateFullName: 'California', zipCode: '92335', displayText: 'Fontana, CA', type: 'city' },
  { city: 'Columbus', state: 'GA', stateFullName: 'Georgia', zipCode: '31901', displayText: 'Columbus, GA', type: 'city' },
  { city: 'Montgomery', state: 'AL', stateFullName: 'Alabama', zipCode: '36104', displayText: 'Montgomery, AL', type: 'city' },
  { city: 'Moreno Valley', state: 'CA', stateFullName: 'California', zipCode: '92553', displayText: 'Moreno Valley, CA', type: 'city' },
  { city: 'Shreveport', state: 'LA', stateFullName: 'Louisiana', zipCode: '71101', displayText: 'Shreveport, LA', type: 'city' },
  { city: 'Aurora', state: 'IL', stateFullName: 'Illinois', zipCode: '60505', displayText: 'Aurora, IL', type: 'city' },
  { city: 'Yonkers', state: 'NY', stateFullName: 'New York', zipCode: '10701', displayText: 'Yonkers, NY', type: 'city' },
  { city: 'Akron', state: 'OH', stateFullName: 'Ohio', zipCode: '44308', displayText: 'Akron, OH', type: 'city' },
  { city: 'Huntington Beach', state: 'CA', stateFullName: 'California', zipCode: '92648', displayText: 'Huntington Beach, CA', type: 'city' },
  { city: 'Little Rock', state: 'AR', stateFullName: 'Arkansas', zipCode: '72201', displayText: 'Little Rock, AR', type: 'city' },
  { city: 'Augusta', state: 'GA', stateFullName: 'Georgia', zipCode: '30901', displayText: 'Augusta, GA', type: 'city' },
  { city: 'Amarillo', state: 'TX', stateFullName: 'Texas', zipCode: '79101', displayText: 'Amarillo, TX', type: 'city' },
  { city: 'Glendale', state: 'CA', stateFullName: 'California', zipCode: '91205', displayText: 'Glendale, CA', type: 'city' },
  { city: 'Mobile', state: 'AL', stateFullName: 'Alabama', zipCode: '36602', displayText: 'Mobile, AL', type: 'city' },
  { city: 'Grand Rapids', state: 'MI', stateFullName: 'Michigan', zipCode: '49503', displayText: 'Grand Rapids, MI', type: 'city' },
  { city: 'Salt Lake City', state: 'UT', stateFullName: 'Utah', zipCode: '84101', displayText: 'Salt Lake City, UT', type: 'city' },
  { city: 'Tallahassee', state: 'FL', stateFullName: 'Florida', zipCode: '32301', displayText: 'Tallahassee, FL', type: 'city' },
  { city: 'Huntsville', state: 'AL', stateFullName: 'Alabama', zipCode: '35801', displayText: 'Huntsville, AL', type: 'city' },
  { city: 'Grand Prairie', state: 'TX', stateFullName: 'Texas', zipCode: '75050', displayText: 'Grand Prairie, TX', type: 'city' },
  { city: 'Knoxville', state: 'TN', stateFullName: 'Tennessee', zipCode: '37902', displayText: 'Knoxville, TN', type: 'city' },
  { city: 'Worcester', state: 'MA', stateFullName: 'Massachusetts', zipCode: '01608', displayText: 'Worcester, MA', type: 'city' },
  { city: 'Newport News', state: 'VA', stateFullName: 'Virginia', zipCode: '23601', displayText: 'Newport News, VA', type: 'city' },
  { city: 'Brownsville', state: 'TX', stateFullName: 'Texas', zipCode: '78520', displayText: 'Brownsville, TX', type: 'city' },
  { city: 'Overland Park', state: 'KS', stateFullName: 'Kansas', zipCode: '66204', displayText: 'Overland Park, KS', type: 'city' },
  { city: 'Santa Clarita', state: 'CA', stateFullName: 'California', zipCode: '91321', displayText: 'Santa Clarita, CA', type: 'city' },
  { city: 'Providence', state: 'RI', stateFullName: 'Rhode Island', zipCode: '02903', displayText: 'Providence, RI', type: 'city' },
  { city: 'Garden Grove', state: 'CA', stateFullName: 'California', zipCode: '92840', displayText: 'Garden Grove, CA', type: 'city' },
  { city: 'Chattanooga', state: 'TN', stateFullName: 'Tennessee', zipCode: '37402', displayText: 'Chattanooga, TN', type: 'city' },
  { city: 'Oceanside', state: 'CA', stateFullName: 'California', zipCode: '92054', displayText: 'Oceanside, CA', type: 'city' },
  { city: 'Jackson', state: 'MS', stateFullName: 'Mississippi', zipCode: '39201', displayText: 'Jackson, MS', type: 'city' },
  { city: 'Fort Lauderdale', state: 'FL', stateFullName: 'Florida', zipCode: '33301', displayText: 'Fort Lauderdale, FL', type: 'city' },
  { city: 'Santa Rosa', state: 'CA', stateFullName: 'California', zipCode: '95404', displayText: 'Santa Rosa, CA', type: 'city' },
  { city: 'Rancho Cucamonga', state: 'CA', stateFullName: 'California', zipCode: '91730', displayText: 'Rancho Cucamonga, CA', type: 'city' },
  { city: 'Port St. Lucie', state: 'FL', stateFullName: 'Florida', zipCode: '34952', displayText: 'Port St. Lucie, FL', type: 'city' },
  { city: 'Tempe', state: 'AZ', stateFullName: 'Arizona', zipCode: '85281', displayText: 'Tempe, AZ', type: 'city' },
  { city: 'Ontario', state: 'CA', stateFullName: 'California', zipCode: '91764', displayText: 'Ontario, CA', type: 'city' },
  { city: 'Vancouver', state: 'WA', stateFullName: 'Washington', zipCode: '98660', displayText: 'Vancouver, WA', type: 'city' },
  { city: 'Cape Coral', state: 'FL', stateFullName: 'Florida', zipCode: '33904', displayText: 'Cape Coral, FL', type: 'city' },
  { city: 'Sioux Falls', state: 'SD', stateFullName: 'South Dakota', zipCode: '57104', displayText: 'Sioux Falls, SD', type: 'city' },
  { city: 'Springfield', state: 'MO', stateFullName: 'Missouri', zipCode: '65806', displayText: 'Springfield, MO', type: 'city' },
  { city: 'Peoria', state: 'AZ', stateFullName: 'Arizona', zipCode: '85345', displayText: 'Peoria, AZ', type: 'city' },
  { city: 'Pembroke Pines', state: 'FL', stateFullName: 'Florida', zipCode: '33025', displayText: 'Pembroke Pines, FL', type: 'city' },
  { city: 'Elk Grove', state: 'CA', stateFullName: 'California', zipCode: '95624', displayText: 'Elk Grove, CA', type: 'city' },
  { city: 'Salem', state: 'OR', stateFullName: 'Oregon', zipCode: '97301', displayText: 'Salem, OR', type: 'city' },
  { city: 'Lancaster', state: 'CA', stateFullName: 'California', zipCode: '93534', displayText: 'Lancaster, CA', type: 'city' },
  { city: 'Corona', state: 'CA', stateFullName: 'California', zipCode: '92879', displayText: 'Corona, CA', type: 'city' },
  { city: 'Eugene', state: 'OR', stateFullName: 'Oregon', zipCode: '97401', displayText: 'Eugene, OR', type: 'city' },
  { city: 'Palmdale', state: 'CA', stateFullName: 'California', zipCode: '93550', displayText: 'Palmdale, CA', type: 'city' },
  { city: 'Salinas', state: 'CA', stateFullName: 'California', zipCode: '93901', displayText: 'Salinas, CA', type: 'city' },
  { city: 'Springfield', state: 'IL', stateFullName: 'Illinois', zipCode: '62701', displayText: 'Springfield, IL', type: 'city' },
  { city: 'Pasadena', state: 'TX', stateFullName: 'Texas', zipCode: '77506', displayText: 'Pasadena, TX', type: 'city' },
  { city: 'Fort Collins', state: 'CO', stateFullName: 'Colorado', zipCode: '80525', displayText: 'Fort Collins, CO', type: 'city' },
  { city: 'Hayward', state: 'CA', stateFullName: 'California', zipCode: '94544', displayText: 'Hayward, CA', type: 'city' },
  { city: 'Pomona', state: 'CA', stateFullName: 'California', zipCode: '91766', displayText: 'Pomona, CA', type: 'city' },
  { city: 'Cary', state: 'NC', stateFullName: 'North Carolina', zipCode: '27511', displayText: 'Cary, NC', type: 'city' },
  { city: 'Rockford', state: 'IL', stateFullName: 'Illinois', zipCode: '61101', displayText: 'Rockford, IL', type: 'city' },
  { city: 'Alexandria', state: 'VA', stateFullName: 'Virginia', zipCode: '22314', displayText: 'Alexandria, VA', type: 'city' },
  { city: 'Escondido', state: 'CA', stateFullName: 'California', zipCode: '92025', displayText: 'Escondido, CA', type: 'city' },
  { city: 'McKinney', state: 'TX', stateFullName: 'Texas', zipCode: '75070', displayText: 'McKinney, TX', type: 'city' },
  { city: 'Kansas City', state: 'KS', stateFullName: 'Kansas', zipCode: '66101', displayText: 'Kansas City, KS', type: 'city' },
  { city: 'Joliet', state: 'IL', stateFullName: 'Illinois', zipCode: '60435', displayText: 'Joliet, IL', type: 'city' },
  { city: 'Sunnyvale', state: 'CA', stateFullName: 'California', zipCode: '94085', displayText: 'Sunnyvale, CA', type: 'city' },
  { city: 'Torrance', state: 'CA', stateFullName: 'California', zipCode: '90501', displayText: 'Torrance, CA', type: 'city' },
  { city: 'Bridgeport', state: 'CT', stateFullName: 'Connecticut', zipCode: '06604', displayText: 'Bridgeport, CT', type: 'city' },
  { city: 'Lakewood', state: 'CO', stateFullName: 'Colorado', zipCode: '80228', displayText: 'Lakewood, CO', type: 'city' },
  { city: 'Hollywood', state: 'FL', stateFullName: 'Florida', zipCode: '33019', displayText: 'Hollywood, FL', type: 'city' },
  { city: 'Paterson', state: 'NJ', stateFullName: 'New Jersey', zipCode: '07505', displayText: 'Paterson, NJ', type: 'city' },
  { city: 'Naperville', state: 'IL', stateFullName: 'Illinois', zipCode: '60540', displayText: 'Naperville, IL', type: 'city' },
  { city: 'Syracuse', state: 'NY', stateFullName: 'New York', zipCode: '13202', displayText: 'Syracuse, NY', type: 'city' },
  { city: 'Mesquite', state: 'TX', stateFullName: 'Texas', zipCode: '75149', displayText: 'Mesquite, TX', type: 'city' },
  { city: 'Dayton', state: 'OH', stateFullName: 'Ohio', zipCode: '45402', displayText: 'Dayton, OH', type: 'city' },
  { city: 'Savannah', state: 'GA', stateFullName: 'Georgia', zipCode: '31401', displayText: 'Savannah, GA', type: 'city' },
  { city: 'Clarksville', state: 'TN', stateFullName: 'Tennessee', zipCode: '37040', displayText: 'Clarksville, TN', type: 'city' },
  { city: 'Orange', state: 'CA', stateFullName: 'California', zipCode: '92866', displayText: 'Orange, CA', type: 'city' },
  { city: 'Pasadena', state: 'CA', stateFullName: 'California', zipCode: '91103', displayText: 'Pasadena, CA', type: 'city' },
  { city: 'Fullerton', state: 'CA', stateFullName: 'California', zipCode: '92835', displayText: 'Fullerton, CA', type: 'city' },
  { city: 'Killeen', state: 'TX', stateFullName: 'Texas', zipCode: '76541', displayText: 'Killeen, TX', type: 'city' },
  { city: 'Frisco', state: 'TX', stateFullName: 'Texas', zipCode: '75034', displayText: 'Frisco, TX', type: 'city' },
  { city: 'Hampton', state: 'VA', stateFullName: 'Virginia', zipCode: '23669', displayText: 'Hampton, VA', type: 'city' },
  { city: 'McAllen', state: 'TX', stateFullName: 'Texas', zipCode: '78501', displayText: 'McAllen, TX', type: 'city' },
  { city: 'Warren', state: 'MI', stateFullName: 'Michigan', zipCode: '48089', displayText: 'Warren, MI', type: 'city' },
  { city: 'Bellevue', state: 'WA', stateFullName: 'Washington', zipCode: '98004', displayText: 'Bellevue, WA', type: 'city' },
  { city: 'West Valley City', state: 'UT', stateFullName: 'Utah', zipCode: '84119', displayText: 'West Valley City, UT', type: 'city' },
  { city: 'Columbia', state: 'SC', stateFullName: 'South Carolina', zipCode: '29201', displayText: 'Columbia, SC', type: 'city' },
  { city: 'Olathe', state: 'KS', stateFullName: 'Kansas', zipCode: '66061', displayText: 'Olathe, KS', type: 'city' },
  { city: 'Sterling Heights', state: 'MI', stateFullName: 'Michigan', zipCode: '48310', displayText: 'Sterling Heights, MI', type: 'city' },
  { city: 'New Haven', state: 'CT', stateFullName: 'Connecticut', zipCode: '06510', displayText: 'New Haven, CT', type: 'city' },
  { city: 'Miramar', state: 'FL', stateFullName: 'Florida', zipCode: '33023', displayText: 'Miramar, FL', type: 'city' },
  { city: 'Waco', state: 'TX', stateFullName: 'Texas', zipCode: '76701', displayText: 'Waco, TX', type: 'city' },
  { city: 'Thousand Oaks', state: 'CA', stateFullName: 'California', zipCode: '91362', displayText: 'Thousand Oaks, CA', type: 'city' },
  { city: 'Cedar Rapids', state: 'IA', stateFullName: 'Iowa', zipCode: '52401', displayText: 'Cedar Rapids, IA', type: 'city' },
  { city: 'Charleston', state: 'SC', stateFullName: 'South Carolina', zipCode: '29403', displayText: 'Charleston, SC', type: 'city' },
  { city: 'Visalia', state: 'CA', stateFullName: 'California', zipCode: '93291', displayText: 'Visalia, CA', type: 'city' },
  { city: 'Topeka', state: 'KS', stateFullName: 'Kansas', zipCode: '66603', displayText: 'Topeka, KS', type: 'city' },
  { city: 'Elizabeth', state: 'NJ', stateFullName: 'New Jersey', zipCode: '07202', displayText: 'Elizabeth, NJ', type: 'city' },
  { city: 'Gainesville', state: 'FL', stateFullName: 'Florida', zipCode: '32601', displayText: 'Gainesville, FL', type: 'city' },
  { city: 'Thornton', state: 'CO', stateFullName: 'Colorado', zipCode: '80229', displayText: 'Thornton, CO', type: 'city' },
  { city: 'Roseville', state: 'CA', stateFullName: 'California', zipCode: '95678', displayText: 'Roseville, CA', type: 'city' },
  { city: 'Carrollton', state: 'TX', stateFullName: 'Texas', zipCode: '75006', displayText: 'Carrollton, TX', type: 'city' },
  { city: 'Coral Springs', state: 'FL', stateFullName: 'Florida', zipCode: '33071', displayText: 'Coral Springs, FL', type: 'city' },
  { city: 'Stamford', state: 'CT', stateFullName: 'Connecticut', zipCode: '06901', displayText: 'Stamford, CT', type: 'city' },
  { city: 'Simi Valley', state: 'CA', stateFullName: 'California', zipCode: '93065', displayText: 'Simi Valley, CA', type: 'city' },
  { city: 'Concord', state: 'CA', stateFullName: 'California', zipCode: '94520', displayText: 'Concord, CA', type: 'city' },
  { city: 'Hartford', state: 'CT', stateFullName: 'Connecticut', zipCode: '06103', displayText: 'Hartford, CT', type: 'city' },
  { city: 'Kent', state: 'WA', stateFullName: 'Washington', zipCode: '98030', displayText: 'Kent, WA', type: 'city' },
  { city: 'Lafayette', state: 'LA', stateFullName: 'Louisiana', zipCode: '70501', displayText: 'Lafayette, LA', type: 'city' },
  { city: 'Midland', state: 'TX', stateFullName: 'Texas', zipCode: '79701', displayText: 'Midland, TX', type: 'city' },
  { city: 'Surprise', state: 'AZ', stateFullName: 'Arizona', zipCode: '85374', displayText: 'Surprise, AZ', type: 'city' },
  { city: 'Denton', state: 'TX', stateFullName: 'Texas', zipCode: '76201', displayText: 'Denton, TX', type: 'city' },
  { city: 'Victorville', state: 'CA', stateFullName: 'California', zipCode: '92395', displayText: 'Victorville, CA', type: 'city' },
  { city: 'Evansville', state: 'IN', stateFullName: 'Indiana', zipCode: '47708', displayText: 'Evansville, IN', type: 'city' },
  { city: 'Santa Clara', state: 'CA', stateFullName: 'California', zipCode: '95050', displayText: 'Santa Clara, CA', type: 'city' },
  { city: 'Abilene', state: 'TX', stateFullName: 'Texas', zipCode: '79601', displayText: 'Abilene, TX', type: 'city' },
  { city: 'Athens', state: 'GA', stateFullName: 'Georgia', zipCode: '30601', displayText: 'Athens, GA', type: 'city' },
  { city: 'Vallejo', state: 'CA', stateFullName: 'California', zipCode: '94590', displayText: 'Vallejo, CA', type: 'city' },
  { city: 'Allentown', state: 'PA', stateFullName: 'Pennsylvania', zipCode: '18102', displayText: 'Allentown, PA', type: 'city' },
  { city: 'Norman', state: 'OK', stateFullName: 'Oklahoma', zipCode: '73019', displayText: 'Norman, OK', type: 'city' },
  { city: 'Beaumont', state: 'TX', stateFullName: 'Texas', zipCode: '77701', displayText: 'Beaumont, TX', type: 'city' },
  { city: 'Independence', state: 'MO', stateFullName: 'Missouri', zipCode: '64050', displayText: 'Independence, MO', type: 'city' },
  { city: 'Murfreesboro', state: 'TN', stateFullName: 'Tennessee', zipCode: '37129', displayText: 'Murfreesboro, TN', type: 'city' },
  { city: 'Ann Arbor', state: 'MI', stateFullName: 'Michigan', zipCode: '48104', displayText: 'Ann Arbor, MI', type: 'city' },
  { city: 'Springfield', state: 'MA', stateFullName: 'Massachusetts', zipCode: '01103', displayText: 'Springfield, MA', type: 'city' },
];

export const filterLocationOptions = (query: string): LocationOption[] => {
  if (!query || query.length < 2) return [];
  
  const searchTerm = query.toLowerCase().trim();
  
  return US_CITIES_DATA.filter(option => {
    const cityMatch = option.city?.toLowerCase().includes(searchTerm);
    const stateMatch = option.state.toLowerCase().includes(searchTerm);
    const stateFullMatch = option.stateFullName.toLowerCase().includes(searchTerm);
    const displayMatch = option.displayText.toLowerCase().includes(searchTerm);
    const zipMatch = option.zipCode?.includes(searchTerm);
    
    return cityMatch || stateMatch || stateFullMatch || displayMatch || zipMatch;
  }).slice(0, 10); // Limit to 10 results for performance
};