[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
# Install only production dependencies needed for WebSocket server
cmds = ['npm ci --omit=dev']

[phases.build]
# Only generate Prisma client, skip Next.js build
cmds = ['npx prisma generate']

[start]
cmd = 'node websocket-server.js'