[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
# Use minimal package.json for WebSocket server only
cmds = ['cp package-websocket.json package.json', 'npm install']

[phases.build]
# Only generate Prisma client
cmds = ['npx prisma generate']

[start]
cmd = 'node websocket-server.js'