[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
# Remove existing package files and use minimal WebSocket-only version
cmds = [
  'rm -f package.json package-lock.json',
  'cp package-websocket.json package.json',
  'npm install --production'
]

[phases.build]
# Only generate Prisma client
cmds = ['npx prisma generate']

[start]
cmd = 'node websocket-server.js'