[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['echo "Skipping build - WebSocket server only"']

[start]
cmd = 'node server.js'